services:
  # Backend
  - type: web
    name: petstore-backend
    runtime: java
    plan: free
    rootDirectory: backend
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/petstore-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: petstore-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: petstore-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: petstore-db
          property: password

  # Frontend
  - type: web
    name: petstore-frontend
    runtime: static
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://petstore-backend.onrender.com/alejos/api/v1

databases:
  - name: petstore-db
    plan: free
    databaseName: petstore
    user: petstore_user
